### ISSUE TITLE
Add indexing rules

### ISSUE THREAD

**Issue by JJ** [antoniogamiz/Perl6-Documentable#29]
You refer back to this repository from perl6/doc#2575 but, in fact, there's no document detailing how indexing actually works. For instance, there are index entries like this `X<BEGIN|Phasers, BEGIN>` and also like this `X<return-rw|control flow, return-rw>`, with categories being indistinctly before or after the comma. Also perl6/doc#2884, which generates incorrect URLs (or at least inconvenient).

**Comment by antoniogamiz** [comment]
I do not know if this resolves the issue => https://github.com/antoniogamiz/Perl6-Documentable/wiki/Knowing-the-system.

It's not completed yet but it covers how `Perl6::Documentable::Registry` is initialized.

**Comment by antoniogamiz** [comment]
I have created a [grammar](https://github.com/antoniogamiz/Perl6-Documentable/blob/master/lib/Perl6/Documentable/Processing/Grammar.pm6) to detect new definitions because is more intuitive. I have also refactor all processing logic to a new module to ease its modification and understanding. Documentation has been updated so if you want to know we deal with this indexing you can check: 

- [process-pod-source](https://github.com/antoniogamiz/Perl6-Documentable#sub-process-pod-source)
- [find-definitions](https://github.com/antoniogamiz/Perl6-Documentable#sub-find-definitions)
- [find-references](https://github.com/antoniogamiz/Perl6-Documentable#sub-find-references)
- [parse-definition-header](https://github.com/antoniogamiz/Perl6-Documentable#sub-parse-definition-header)

**Comment by antoniogamiz** [comment]
Indexing rules are quite clear in `/docs` directory so I think this issue is solved.
